-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgYfQN9vUmFgtM+DNt
WRvvlW0k6OaTbWgSCdfdR3EUmGCgCgYIKoZIzj0DAQehRANCAASZHfar0jhyVExI
PB+cOWN7ml9RoK+wCdsHRdogsv/ri2STO8PRy6xClokzp401uG3NFzoSq0VkX9A/
c/VuBD9D
-----END PRIVATE KEY-----