-- ─────────────────────────────────────────────────────────────────────────────
-- 017_exercise_catalog.sql
-- Adds exercise_category column and bulk-inserts the full exercise catalog.
-- Safe to re-run: uses WHERE NOT EXISTS to skip duplicates by name.
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.exercises
  add column if not exists exercise_category text;

-- Back-fill existing seeded exercises with a sensible default
update public.exercises
  set exercise_category = 'Strength'
  where exercise_category is null and is_custom = false;

-- ─── BULK INSERT — skips any exercise whose name already exists ────────────
insert into public.exercises (name, muscle_group, secondary_muscle, equipment_type, is_custom, exercise_category)
select v.name, v.muscle_group, v.secondary_muscle, v.equipment_type, false, v.exercise_category
from (values
  -- CHEST ──────────────────────────────────────────────────────────────────
  ('Barbell Bench Press','Chest','Triceps; Shoulders','Barbell','Strength'),
  ('Incline Barbell Bench Press','Chest','Triceps; Shoulders','Barbell','Strength'),
  ('Decline Barbell Bench Press','Chest','Triceps; Shoulders','Barbell','Strength'),
  ('Dumbbell Bench Press','Chest','Triceps; Shoulders','Dumbbell','Strength'),
  ('Incline Dumbbell Press','Chest','Triceps; Shoulders','Dumbbell','Strength'),
  ('Decline Dumbbell Press','Chest','Triceps; Shoulders','Dumbbell','Strength'),
  ('Dumbbell Pullover','Chest','Lats; Triceps','Dumbbell','Strength'),
  ('Pec Deck Machine','Chest','Shoulders','Machine','Strength'),
  ('Cable Chest Fly','Chest','Shoulders','Cable','Strength'),
  ('High Cable Chest Fly','Chest','Shoulders','Cable','Strength'),
  ('Low Cable Chest Fly','Chest','Shoulders','Cable','Strength'),
  ('Cable Crossover','Chest','Shoulders; Triceps','Cable','Strength'),
  ('Incline Cable Fly','Chest','Shoulders','Cable','Strength'),
  ('Chest Dips','Chest','Triceps; Shoulders','Bodyweight','Strength'),
  ('Weighted Chest Dips','Chest','Triceps; Shoulders','Bodyweight','Strength'),
  ('Push-Ups','Chest','Triceps; Shoulders','Bodyweight','Calisthenics'),
  ('Wide Grip Push-Ups','Chest','Shoulders','Bodyweight','Calisthenics'),
  ('Diamond Push-Ups','Chest','Triceps','Bodyweight','Calisthenics'),
  ('Decline Push-Ups','Chest','Shoulders; Triceps','Bodyweight','Calisthenics'),
  ('Incline Push-Ups','Chest','Triceps','Bodyweight','Calisthenics'),
  ('Archer Push-Ups','Chest','Triceps; Shoulders','Bodyweight','Calisthenics'),
  ('Pike Push-Ups','Shoulders','Triceps; Chest','Bodyweight','Calisthenics'),
  ('Smith Machine Bench Press','Chest','Triceps; Shoulders','Smith Machine','Strength'),
  ('Smith Machine Incline Press','Chest','Triceps; Shoulders','Smith Machine','Strength'),
  ('Hammer Strength Chest Press','Chest','Triceps; Shoulders','Machine','Strength'),
  ('Hammer Strength Incline Press','Chest','Triceps; Shoulders','Machine','Strength'),
  ('Plate Loaded Chest Fly Machine','Chest','Shoulders','Machine','Strength'),
  ('Incline Machine Press','Chest','Triceps; Shoulders','Machine','Strength'),
  ('Seated Machine Chest Press','Chest','Triceps; Shoulders','Machine','Strength'),
  -- SHOULDERS ──────────────────────────────────────────────────────────────
  ('Barbell Overhead Press','Shoulders','Triceps; Traps','Barbell','Strength'),
  ('Seated Barbell Overhead Press','Shoulders','Triceps; Traps','Barbell','Strength'),
  ('Dumbbell Shoulder Press','Shoulders','Triceps','Dumbbell','Strength'),
  ('Seated Dumbbell Shoulder Press','Shoulders','Triceps','Dumbbell','Strength'),
  ('Arnold Press','Shoulders','Triceps; Chest','Dumbbell','Strength'),
  ('Dumbbell Lateral Raise','Shoulders','Traps','Dumbbell','Strength'),
  ('Seated Dumbbell Lateral Raise','Shoulders','Traps','Dumbbell','Strength'),
  ('Cable Lateral Raise','Shoulders','Traps','Cable','Strength'),
  ('Single Arm Cable Lateral Raise','Shoulders','Traps','Cable','Strength'),
  ('Lateral Raise Machine','Shoulders','Traps','Machine','Strength'),
  ('Dumbbell Front Raise','Shoulders','Chest; Traps','Dumbbell','Strength'),
  ('Barbell Front Raise','Shoulders','Traps','Barbell','Strength'),
  ('Cable Front Raise','Shoulders','Traps','Cable','Strength'),
  ('Plate Front Raise','Shoulders','Traps','Barbell','Strength'),
  ('Rear Delt Fly','Shoulders','Mid-Upper Back','Dumbbell','Strength'),
  ('Seated Rear Delt Fly','Shoulders','Mid-Upper Back','Dumbbell','Strength'),
  ('Cable Rear Delt Fly','Shoulders','Mid-Upper Back','Cable','Strength'),
  ('Reverse Pec Deck','Shoulders','Mid-Upper Back','Machine','Strength'),
  ('Face Pulls','Shoulders','Mid-Upper Back; Biceps','Cable','Strength'),
  ('Upright Row','Shoulders','Traps; Biceps','Barbell','Strength'),
  ('Dumbbell Upright Row','Shoulders','Traps; Biceps','Dumbbell','Strength'),
  ('Cable Upright Row','Shoulders','Traps; Biceps','Cable','Strength'),
  ('Shoulder Press Machine','Shoulders','Triceps','Machine','Strength'),
  ('Smith Machine Overhead Press','Shoulders','Triceps','Smith Machine','Strength'),
  ('Rear Delt Row','Shoulders','Mid-Upper Back','Dumbbell','Strength'),
  ('Cable Y Raise','Shoulders','Mid-Upper Back','Cable','Strength'),
  ('Band Pull Apart','Shoulders','Mid-Upper Back','Resistance Band','Strength'),
  -- TRAPS ──────────────────────────────────────────────────────────────────
  ('Barbell Shrugs','Traps','Shoulders','Barbell','Strength'),
  ('Dumbbell Shrugs','Traps','Shoulders','Dumbbell','Strength'),
  ('Cable Shrugs','Traps','Shoulders','Cable','Strength'),
  ('Behind the Back Barbell Shrug','Traps','Shoulders','Barbell','Strength'),
  ('Farmers Carry','Traps','Forearms; Core','Dumbbell','Strength'),
  ('Hex Bar Farmers Carry','Traps','Forearms; Core','Barbell','Strength'),
  ('Trap Bar Shrug','Traps','Shoulders','Barbell','Strength'),
  -- TRICEPS ────────────────────────────────────────────────────────────────
  ('Skull Crushers','Triceps','Shoulders','Barbell','Strength'),
  ('Dumbbell Skull Crushers','Triceps','Shoulders','Dumbbell','Strength'),
  ('Close Grip Bench Press','Triceps','Chest; Shoulders','Barbell','Strength'),
  ('Tricep Dips','Triceps','Chest; Shoulders','Bodyweight','Calisthenics'),
  ('Weighted Tricep Dips','Triceps','Chest; Shoulders','Bodyweight','Strength'),
  ('Overhand Pushdowns','Triceps',null,'Cable','Strength'),
  ('Underhand Pushdowns','Triceps',null,'Cable','Strength'),
  ('Rope Pushdowns','Triceps',null,'Cable','Strength'),
  ('Single Arm Cable Pushdown','Triceps',null,'Cable','Strength'),
  ('Standing Cable Tricep Extension','Triceps',null,'Cable','Strength'),
  ('Overhead Cable Tricep Extension','Triceps',null,'Cable','Strength'),
  ('Rope Overhead Tricep Extension','Triceps',null,'Cable','Strength'),
  ('Cross Body Cable Extension','Triceps',null,'Cable','Strength'),
  ('Cable Kickback','Triceps',null,'Cable','Strength'),
  ('Dumbbell Kickback','Triceps',null,'Dumbbell','Strength'),
  ('Katana Extensions','Triceps',null,'Cable','Strength'),
  ('Tricep Machine Press','Triceps',null,'Machine','Strength'),
  ('Seated Overhead Dumbbell Extension','Triceps',null,'Dumbbell','Strength'),
  ('Single Arm Dumbbell Overhead Extension','Triceps',null,'Dumbbell','Strength'),
  ('JM Press','Triceps','Chest','Barbell','Strength'),
  ('Tate Press','Triceps',null,'Dumbbell','Strength'),
  -- BICEPS ─────────────────────────────────────────────────────────────────
  ('Barbell Curl','Biceps','Forearms','Barbell','Strength'),
  ('EZ Bar Curl','Biceps','Forearms','Barbell','Strength'),
  ('Dumbbell Curl','Biceps','Forearms','Dumbbell','Strength'),
  ('Alternating Dumbbell Curl','Biceps','Forearms','Dumbbell','Strength'),
  ('Hammer Curl','Biceps','Forearms; Brachialis','Dumbbell','Strength'),
  ('Cross Body Hammer Curl','Biceps','Forearms; Brachialis','Dumbbell','Strength'),
  ('Preacher Curl','Biceps','Forearms','Barbell','Strength'),
  ('Dumbbell Preacher Curl','Biceps','Forearms','Dumbbell','Strength'),
  ('Concentration Curl','Biceps','Forearms','Dumbbell','Strength'),
  ('Spider Curl','Biceps','Forearms','Dumbbell','Strength'),
  ('Incline Dumbbell Curl','Biceps','Forearms','Dumbbell','Strength'),
  ('Cable Curl','Biceps','Forearms','Cable','Strength'),
  ('Single Arm Cable Curl','Biceps','Forearms','Cable','Strength'),
  ('Overhead Cable Curl','Biceps','Forearms','Cable','Strength'),
  ('EZ Bar Preacher Curl','Biceps','Forearms','Barbell','Strength'),
  ('Machine Preacher Curl','Biceps','Forearms','Machine','Strength'),
  ('Machine Bicep Curl','Biceps','Forearms','Machine','Strength'),
  ('Resistance Band Curl','Biceps','Forearms','Resistance Band','Strength'),
  ('Chin-Ups','Biceps','Lats; Mid-Upper Back','Bodyweight','Calisthenics'),
  ('Weighted Chin-Ups','Biceps','Lats; Mid-Upper Back','Bodyweight','Strength'),
  ('Zottman Curl','Biceps','Forearms; Brachialis','Dumbbell','Strength'),
  ('Reverse Curl','Biceps','Forearms; Brachialis','Barbell','Strength'),
  ('Reverse EZ Bar Curl','Biceps','Forearms; Brachialis','Barbell','Strength'),
  -- LATS ───────────────────────────────────────────────────────────────────
  ('Lat Pulldown','Lats','Biceps; Mid-Upper Back','Cable','Strength'),
  ('Wide Grip Lat Pulldown','Lats','Biceps; Mid-Upper Back','Cable','Strength'),
  ('Close Grip Lat Pulldown','Lats','Biceps','Cable','Strength'),
  ('Underhand Lat Pulldown','Lats','Biceps','Cable','Strength'),
  ('Single Arm Lat Pulldown','Lats','Biceps','Cable','Strength'),
  ('Straight Arm Pulldown','Lats','Triceps; Core','Cable','Strength'),
  ('Kneeling Single Arm Lat Pulldown','Lats','Biceps','Cable','Strength'),
  ('Pull-Ups','Lats','Biceps; Mid-Upper Back','Bodyweight','Calisthenics'),
  ('Weighted Pull-Ups','Lats','Biceps; Mid-Upper Back','Bodyweight','Strength'),
  ('Neutral Grip Pull-Ups','Lats','Biceps','Bodyweight','Calisthenics'),
  ('Wide Grip Pull-Ups','Lats','Mid-Upper Back','Bodyweight','Calisthenics'),
  ('Assisted Pull-Ups','Lats','Biceps','Machine','Strength'),
  ('Lat Pullover','Lats','Triceps; Chest','Dumbbell','Strength'),
  ('Cable Pullover','Lats','Triceps; Chest','Cable','Strength'),
  ('Machine Pullover','Lats','Triceps; Chest','Machine','Strength'),
  ('Seated Lat Row','Lats','Biceps; Mid-Upper Back','Cable','Strength'),
  ('Seated Single Arm Lat Row','Lats','Biceps','Cable','Strength'),
  ('One Arm Pulldown','Lats','Biceps','Cable','Strength'),
  ('Muscle-Up','Lats','Biceps; Triceps; Chest','Bodyweight','Calisthenics'),
  ('Ring Muscle-Up','Lats','Biceps; Triceps; Chest','Bodyweight','Calisthenics'),
  ('Front Lever','Lats','Core; Shoulders','Bodyweight','Calisthenics'),
  ('Tucked Front Lever','Lats','Core','Bodyweight','Calisthenics'),
  ('Typewriter Pull-Up','Lats','Biceps','Bodyweight','Calisthenics'),
  ('One Arm Pull-Up','Lats','Biceps; Core','Bodyweight','Calisthenics'),
  ('Commando Pull-Up','Lats','Biceps','Bodyweight','Calisthenics'),
  -- MID-UPPER BACK ─────────────────────────────────────────────────────────
  ('Inverted Row','Mid-Upper Back','Biceps; Lats','Bodyweight','Calisthenics'),
  ('Barbell Row','Mid-Upper Back','Biceps; Lats','Barbell','Strength'),
  ('Pendlay Row','Mid-Upper Back','Biceps; Lats','Barbell','Strength'),
  ('T-Bar Row','Mid-Upper Back','Biceps; Lats','Barbell','Strength'),
  ('T-Bar Row (Machine)','Mid-Upper Back','Biceps; Lats','Machine','Strength'),
  ('Seated Cable Row','Mid-Upper Back','Biceps; Lats','Cable','Strength'),
  ('Wide Grip Cable Row','Mid-Upper Back','Biceps; Lats','Cable','Strength'),
  ('Single Arm Dumbbell Row','Mid-Upper Back','Biceps; Lats','Dumbbell','Strength'),
  ('Meadows Row','Mid-Upper Back','Biceps; Lats','Barbell','Strength'),
  ('Chest Supported Row','Mid-Upper Back','Biceps','Dumbbell','Strength'),
  ('Chest Supported Machine Row','Mid-Upper Back','Biceps','Machine','Strength'),
  ('Hammer Strength Row','Mid-Upper Back','Biceps; Lats','Machine','Strength'),
  ('Cable Single Arm Row','Mid-Upper Back','Biceps','Cable','Strength'),
  ('Dumbbell Rear Delt Row','Shoulders','Mid-Upper Back','Dumbbell','Strength'),
  ('Rack Pull','Mid-Upper Back','Traps; Glutes','Barbell','Strength'),
  ('Hyperextension','Mid-Upper Back','Glutes; Hamstrings','Bodyweight','Strength'),
  ('Weighted Hyperextension','Mid-Upper Back','Glutes; Hamstrings','Machine','Strength'),
  ('Block Pull','Mid-Upper Back','Traps; Glutes','Barbell','Strength'),
  ('Australian Pull-Up','Mid-Upper Back','Biceps','Bodyweight','Calisthenics'),
  ('Ring Row','Mid-Upper Back','Biceps','Bodyweight','Calisthenics'),
  ('Landmine Row','Mid-Upper Back','Biceps','Barbell','Strength'),
  -- LOWER BACK ─────────────────────────────────────────────────────────────
  ('Reverse Hyperextension','Glutes','Hamstrings; Lower Back','Machine','Strength'),
  ('Good Mornings','Hamstrings','Lower Back; Glutes','Barbell','Strength'),
  ('Jefferson Curl','Lower Back','Hamstrings','Barbell','Mobility'),
  -- DEADLIFTS / OVERALL ────────────────────────────────────────────────────
  ('Deadlift','Overall','Hamstrings; Glutes; Back; Traps','Barbell','Strength'),
  ('Sumo Deadlift','Overall','Hamstrings; Glutes; Adductors','Barbell','Strength'),
  ('Romanian Deadlift','Hamstrings','Glutes; Lower Back','Barbell','Strength'),
  ('Dumbbell Romanian Deadlift','Hamstrings','Glutes; Lower Back','Dumbbell','Strength'),
  ('Single Leg Romanian Deadlift','Hamstrings','Glutes; Core','Dumbbell','Strength'),
  ('Trap Bar Deadlift','Overall','Hamstrings; Glutes; Quads','Barbell','Strength'),
  ('Stiff Leg Deadlift','Hamstrings','Lower Back; Glutes','Barbell','Strength'),
  ('Cable Pull Through','Glutes','Hamstrings','Cable','Strength'),
  ('Paused Deadlift','Overall','Hamstrings; Glutes; Back','Barbell','Strength'),
  -- QUADS ──────────────────────────────────────────────────────────────────
  ('Barbell Back Squat','Quads','Glutes; Hamstrings; Core','Barbell','Strength'),
  ('Barbell Front Squat','Quads','Glutes; Core','Barbell','Strength'),
  ('Low Bar Squat','Quads','Glutes; Hamstrings','Barbell','Strength'),
  ('Hack Squat','Quads','Glutes; Hamstrings','Machine','Strength'),
  ('Leg Press','Quads','Glutes; Hamstrings','Machine','Strength'),
  ('Wide Stance Leg Press','Glutes','Quads; Hamstrings','Machine','Strength'),
  ('Single Leg Press','Quads','Glutes','Machine','Strength'),
  ('Leg Extension','Quads',null,'Machine','Strength'),
  ('Single Leg Extension','Quads',null,'Machine','Strength'),
  ('Goblet Squat','Quads','Glutes; Core','Dumbbell','Strength'),
  ('Dumbbell Squat','Quads','Glutes; Hamstrings','Dumbbell','Strength'),
  ('Bulgarian Split Squat','Quads','Glutes; Hamstrings','Dumbbell','Strength'),
  ('Barbell Bulgarian Split Squat','Quads','Glutes; Hamstrings','Barbell','Strength'),
  ('Walking Lunges','Quads','Glutes; Hamstrings','Dumbbell','Strength'),
  ('Barbell Walking Lunges','Quads','Glutes; Hamstrings','Barbell','Strength'),
  ('Reverse Lunges','Quads','Glutes','Dumbbell','Strength'),
  ('Lateral Lunges','Quads','Adductors; Glutes','Dumbbell','Strength'),
  ('Curtsy Lunges','Glutes','Quads; Adductors','Dumbbell','Strength'),
  ('Dumbbell Step-Ups','Quads','Glutes; Hamstrings','Dumbbell','Strength'),
  ('Barbell Step-Ups','Quads','Glutes; Hamstrings','Barbell','Strength'),
  ('Smith Machine Squat','Quads','Glutes; Hamstrings','Smith Machine','Strength'),
  ('Smith Machine Bulgarian Split Squat','Quads','Glutes','Smith Machine','Strength'),
  ('Smith Machine Reverse Lunge','Quads','Glutes','Smith Machine','Strength'),
  ('Sissy Squat','Quads',null,'Bodyweight','Strength'),
  ('Pistol Squat','Quads','Glutes; Core','Bodyweight','Calisthenics'),
  ('Safety Bar Squat','Quads','Glutes; Hamstrings','Barbell','Strength'),
  ('Zercher Squat','Quads','Core; Glutes','Barbell','Strength'),
  ('Paused Squat','Quads','Glutes; Hamstrings','Barbell','Strength'),
  ('Belt Squat','Quads','Glutes; Hamstrings','Machine','Strength'),
  ('Pendulum Squat','Quads','Glutes','Machine','Strength'),
  ('Cable Squat','Quads','Glutes','Cable','Strength'),
  ('Landmine Squat','Quads','Glutes','Barbell','Strength'),
  -- HAMSTRINGS ─────────────────────────────────────────────────────────────
  ('Leg Curl','Hamstrings',null,'Machine','Strength'),
  ('Seated Leg Curl','Hamstrings',null,'Machine','Strength'),
  ('Single Leg Curl','Hamstrings',null,'Machine','Strength'),
  ('Nordic Curl','Hamstrings',null,'Bodyweight','Strength'),
  ('Kettlebell Romanian Deadlift','Hamstrings','Glutes; Lower Back','Kettlebell','Strength'),
  ('Cable Romanian Deadlift','Hamstrings','Glutes','Cable','Strength'),
  ('Banded RDL','Hamstrings','Glutes','Resistance Band','Strength'),
  ('Landmine Hip Hinge','Hamstrings','Glutes; Lower Back','Barbell','Strength'),
  ('Smith Machine Romanian Deadlift','Hamstrings','Glutes; Lower Back','Smith Machine','Strength'),
  -- GLUTES ─────────────────────────────────────────────────────────────────
  ('Hip Thrust','Glutes','Hamstrings','Barbell','Strength'),
  ('Dumbbell Hip Thrust','Glutes','Hamstrings','Dumbbell','Strength'),
  ('Machine Hip Thrust','Glutes','Hamstrings','Machine','Strength'),
  ('KAS Glute Bridge','Glutes','Hamstrings','Barbell','Strength'),
  ('Single Leg Hip Thrust','Glutes','Hamstrings','Bodyweight','Strength'),
  ('Glute Bridge','Glutes','Hamstrings','Bodyweight','Strength'),
  ('Donkey Kicks','Glutes',null,'Bodyweight','Strength'),
  ('Cable Donkey Kicks','Glutes',null,'Cable','Strength'),
  ('Glute Kickback Machine','Glutes',null,'Machine','Strength'),
  ('Cable Hip Abduction','Glutes','Abductors','Cable','Strength'),
  ('Hip Abduction Machine','Glutes','Abductors','Machine','Strength'),
  ('Hip Adduction Machine','Adductors',null,'Machine','Strength'),
  ('Glute Focused Back Extension','Glutes','Hamstrings; Lower Back','Machine','Strength'),
  ('Hip Abductor Machine','Glutes','Abductors','Machine','Strength'),
  ('Smith Machine Hip Thrust','Glutes','Hamstrings','Smith Machine','Strength'),
  ('Banded Hip Thrust','Glutes','Hamstrings','Resistance Band','Strength'),
  ('Banded Clamshell','Glutes','Abductors','Resistance Band','Strength'),
  ('Lateral Band Walk','Glutes','Abductors','Resistance Band','Strength'),
  -- CALVES ─────────────────────────────────────────────────────────────────
  ('Calf Raise (Standing)','Calves',null,'Machine','Strength'),
  ('Seated Calf Raise','Calves',null,'Machine','Strength'),
  ('Leg Press Calf Raise','Calves',null,'Machine','Strength'),
  ('Dumbbell Calf Raise','Calves',null,'Dumbbell','Strength'),
  ('Barbell Calf Raise','Calves',null,'Barbell','Strength'),
  ('Single Leg Calf Raise','Calves',null,'Bodyweight','Strength'),
  ('Tibialis Raise','Tibialis',null,'Bodyweight','Strength'),
  -- CORE ───────────────────────────────────────────────────────────────────
  ('Plank','Core','Shoulders','Bodyweight','Core'),
  ('Side Plank','Core','Shoulders; Glutes','Bodyweight','Core'),
  ('Long Lever Plank','Core','Shoulders','Bodyweight','Core'),
  ('Ab Wheel Rollout','Core','Lats; Shoulders','Bodyweight','Core'),
  ('Hanging Leg Raise','Core','Lats','Bodyweight','Core'),
  ('Hanging Knee Raise','Core','Lats','Bodyweight','Core'),
  ('Toes to Bar','Core','Lats','Bodyweight','Core'),
  ('Captain''s Chair Leg Raise','Core',null,'Machine','Core'),
  ('Decline Sit-Up','Core',null,'Bodyweight','Core'),
  ('Cable Crunch','Core',null,'Cable','Core'),
  ('Machine Crunch','Core',null,'Machine','Core'),
  ('Bicycle Crunch','Core',null,'Bodyweight','Core'),
  ('Russian Twist','Core',null,'Bodyweight','Core'),
  ('Weighted Russian Twist','Core',null,'Dumbbell','Core'),
  ('Dead Bug','Core',null,'Bodyweight','Core'),
  ('Bird Dog','Core','Lower Back','Bodyweight','Core'),
  ('Hollow Body Hold','Core',null,'Bodyweight','Calisthenics'),
  ('V-Up','Core',null,'Bodyweight','Core'),
  ('Leg Raises','Core',null,'Bodyweight','Core'),
  ('Flutter Kicks','Core',null,'Bodyweight','Core'),
  ('Pallof Press','Core',null,'Cable','Core'),
  ('Woodchop','Core','Shoulders','Cable','Core'),
  ('Dragon Flag','Core','Lats','Bodyweight','Calisthenics'),
  ('L-Sit','Core','Triceps; Lats','Bodyweight','Calisthenics'),
  ('McGill Curl Up','Core','Lower Back','Bodyweight','Core'),
  ('Reverse Crunch','Core',null,'Bodyweight','Core'),
  ('Landmine Rotation','Core','Shoulders','Barbell','Core'),
  ('Suitcase Carry','Core','Traps; Forearms','Dumbbell','Strength'),
  ('Barbell Rollout','Core','Lats','Barbell','Core'),
  -- CALISTHENICS ────────────────────────────────────────────────────────────
  ('Back Lever','Shoulders','Chest; Lats','Bodyweight','Calisthenics'),
  ('Human Flag','Core','Shoulders; Lats','Bodyweight','Calisthenics'),
  ('Planche','Shoulders','Chest; Triceps; Core','Bodyweight','Calisthenics'),
  ('Tucked Planche','Shoulders','Chest; Core','Bodyweight','Calisthenics'),
  ('Handstand','Shoulders','Core; Triceps','Bodyweight','Calisthenics'),
  ('Handstand Push-Up','Shoulders','Triceps; Core','Bodyweight','Calisthenics'),
  ('Freestanding Handstand Push-Up','Shoulders','Triceps; Core','Bodyweight','Calisthenics'),
  ('Skin the Cat','Shoulders','Lats; Core','Bodyweight','Calisthenics'),
  ('Ring Dip','Chest','Triceps; Shoulders','Bodyweight','Calisthenics'),
  ('Ring Push-Up','Chest','Triceps; Shoulders','Bodyweight','Calisthenics'),
  ('Bear Crawl','Core','Shoulders; Quads','Bodyweight','Calisthenics'),
  ('Crab Walk','Core','Shoulders; Triceps','Bodyweight','Calisthenics'),
  -- FOREARMS ────────────────────────────────────────────────────────────────
  ('Wrist Roller','Forearms',null,'Other','Strength'),
  ('Barbell Wrist Curl','Forearms',null,'Barbell','Strength'),
  ('Dumbbell Wrist Curl','Forearms',null,'Dumbbell','Strength'),
  ('Reverse Wrist Curl','Forearms',null,'Barbell','Strength'),
  ('Plate Pinch','Forearms',null,'Other','Strength'),
  ('Dead Hang','Forearms','Lats; Shoulders','Bodyweight','Calisthenics'),
  -- CARDIO ──────────────────────────────────────────────────────────────────
  ('Box Jump','Quads','Glutes; Calves','Bodyweight','Cardio'),
  ('Broad Jump','Quads','Glutes; Hamstrings','Bodyweight','Cardio'),
  ('Vertical Jump','Quads','Glutes; Calves','Bodyweight','Cardio'),
  ('Burpees','Overall','Core; Shoulders','Bodyweight','Cardio'),
  ('Jump Squat','Quads','Glutes; Calves','Bodyweight','Cardio'),
  ('Jump Lunge','Quads','Glutes','Bodyweight','Cardio'),
  ('Sprints','Overall','Quads; Hamstrings; Calves','Bodyweight','Cardio'),
  ('Treadmill Run','Overall','Quads; Hamstrings; Calves','Machine','Cardio'),
  ('Treadmill Walk (Incline)','Overall','Calves; Glutes','Machine','Cardio'),
  ('Stationary Bike','Quads','Hamstrings; Calves','Machine','Cardio'),
  ('Assault Bike','Overall','Quads; Shoulders','Machine','Cardio'),
  ('Rowing Machine','Overall','Lats; Hamstrings; Core','Machine','Cardio'),
  ('Ski Erg','Overall','Lats; Core; Shoulders','Machine','Cardio'),
  ('Stair Climber','Quads','Glutes; Calves','Machine','Cardio'),
  ('Elliptical','Overall','Quads; Hamstrings','Machine','Cardio'),
  ('Jump Rope','Calves','Overall; Core','Other','Cardio'),
  ('Battle Ropes','Overall','Shoulders; Core','Other','Cardio'),
  ('Sled Push','Quads','Glutes; Hamstrings','Other','Cardio'),
  ('Sled Pull','Hamstrings','Glutes; Back','Other','Cardio'),
  ('Tire Flip','Overall','Hamstrings; Back; Shoulders','Other','Cardio'),
  -- KETTLEBELL ──────────────────────────────────────────────────────────────
  ('Kettlebell Swing','Glutes','Hamstrings; Core; Shoulders','Kettlebell','Strength'),
  ('Kettlebell Goblet Squat','Quads','Glutes; Core','Kettlebell','Strength'),
  ('Kettlebell Clean','Overall','Quads; Shoulders; Core','Kettlebell','Strength'),
  ('Kettlebell Snatch','Overall','Shoulders; Core; Quads','Kettlebell','Strength'),
  ('Kettlebell Press','Shoulders','Triceps; Core','Kettlebell','Strength'),
  ('Kettlebell Row','Mid-Upper Back','Biceps; Lats','Kettlebell','Strength'),
  ('Kettlebell Turkish Get-Up','Overall','Core; Shoulders','Kettlebell','Strength'),
  ('Kettlebell Windmill','Core','Shoulders; Hamstrings','Kettlebell','Strength'),
  ('Kettlebell Figure 8','Core','Quads; Shoulders','Kettlebell','Strength'),
  ('Kettlebell Halo','Shoulders','Core','Kettlebell','Strength'),
  -- LANDMINE ────────────────────────────────────────────────────────────────
  ('Landmine Press','Shoulders','Chest; Triceps','Barbell','Strength'),
  ('Paused Bench Press','Chest','Triceps; Shoulders','Barbell','Strength'),
  -- RESISTANCE BAND ─────────────────────────────────────────────────────────
  ('Banded Pull Apart','Shoulders','Mid-Upper Back','Resistance Band','Strength'),
  ('Banded Face Pull','Shoulders','Mid-Upper Back','Resistance Band','Strength'),
  ('Banded Curl','Biceps','Forearms','Resistance Band','Strength'),
  ('Banded Tricep Extension','Triceps',null,'Resistance Band','Strength'),
  ('Banded Row','Mid-Upper Back','Biceps','Resistance Band','Strength'),
  ('Banded Squat','Quads','Glutes','Resistance Band','Strength'),
  ('Banded Lateral Raise','Shoulders',null,'Resistance Band','Strength'),
  -- MOBILITY ────────────────────────────────────────────────────────────────
  ('Foam Rolling - Quads','Quads',null,'Other','Mobility'),
  ('Foam Rolling - IT Band','Quads','Glutes','Other','Mobility'),
  ('Foam Rolling - Hamstrings','Hamstrings',null,'Other','Mobility'),
  ('Foam Rolling - Upper Back','Mid-Upper Back',null,'Other','Mobility'),
  ('Foam Rolling - Lats','Lats',null,'Other','Mobility'),
  ('Foam Rolling - Calves','Calves',null,'Other','Mobility'),
  ('Hip Flexor Stretch','Hip Flexors',null,'Bodyweight','Mobility'),
  ('Pigeon Pose','Glutes','Hip Flexors','Bodyweight','Mobility'),
  ('World''s Greatest Stretch','Overall',null,'Bodyweight','Mobility'),
  ('90-90 Hip Stretch','Glutes','Hip Flexors','Bodyweight','Mobility'),
  ('Couch Stretch','Hip Flexors','Quads','Bodyweight','Mobility'),
  ('Thoracic Spine Rotation','Mid-Upper Back',null,'Bodyweight','Mobility'),
  ('Cat Cow','Lower Back','Core','Bodyweight','Mobility'),
  ('Child''s Pose','Lower Back','Lats; Shoulders','Bodyweight','Mobility'),
  ('Thread the Needle','Mid-Upper Back','Shoulders','Bodyweight','Mobility'),
  ('Shoulder Dislocates','Shoulders',null,'Other','Mobility'),
  ('Wrist Circles','Forearms',null,'Bodyweight','Mobility'),
  ('Ankle Circles','Calves',null,'Bodyweight','Mobility'),
  ('Hip Circles','Glutes','Hip Flexors','Bodyweight','Mobility'),
  ('Leg Swings','Hamstrings','Hip Flexors','Bodyweight','Mobility'),
  ('Arm Circles','Shoulders',null,'Bodyweight','Mobility'),
  ('Inchworm','Overall','Hamstrings; Shoulders','Bodyweight','Mobility'),
  ('Toe Touch','Hamstrings','Lower Back','Bodyweight','Mobility'),
  ('Standing Quad Stretch','Quads',null,'Bodyweight','Mobility'),
  ('Standing Hamstring Stretch','Hamstrings',null,'Bodyweight','Mobility'),
  ('Seated Hamstring Stretch','Hamstrings','Lower Back','Bodyweight','Mobility'),
  ('Chest Stretch','Chest','Shoulders','Bodyweight','Mobility'),
  ('Cross Body Shoulder Stretch','Shoulders',null,'Bodyweight','Mobility'),
  ('Overhead Tricep Stretch','Triceps',null,'Bodyweight','Mobility'),
  ('Bicep Wall Stretch','Biceps','Chest','Bodyweight','Mobility'),
  ('Calf Stretch','Calves',null,'Bodyweight','Mobility'),
  ('Lat Stretch','Lats',null,'Bodyweight','Mobility'),
  ('Glute Stretch','Glutes',null,'Bodyweight','Mobility'),
  ('Squat to Stand','Quads','Hamstrings; Ankles','Bodyweight','Mobility')
) as v(name, muscle_group, secondary_muscle, equipment_type, exercise_category)
where not exists (
  select 1 from public.exercises e
  where lower(e.name) = lower(v.name)
    and e.is_custom = false
);
